# Generated by Django 4.1.3 on 2022-11-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_barang_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
                ('harga', models.BigIntegerField()),
                ('waktu_beli', models.DateTimeField(auto_now_add=True)),
                ('komen', models.CharField(max_length=150)),
            ],
        ),
    ]
